import { useQuery } from "@apollo/client";
import Head from "next/head";
import Feed from "../components/Feed";
import PostBox from "../components/PostBox";
import SubredditRows from "../components/SubredditRows";
import { GET_SUBREDDIT_BY_LIMITS } from "../graphql/queries";

export default function Home() {
  const { data } = useQuery(GET_SUBREDDIT_BY_LIMITS, {
    variables: {
      limit: 10,
    },
  });
  const subreddits = data?.getSubredditListLimit;
  return (
    <div className=" my-7 mx-auto max-w-4xl">
      <Head>
        <title>Reddit Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PostBox />

      <div className="flex">
        <Feed />

        <div className="sticky top-36 mt-5 bg-white h-fit min-w-[300px] hidden lg:inline rounded-md border border-gray-300 mx-5">
          <p className="text-md font-bold p-4 mb-1 pb-3">Top Communities</p>

          <div>
            {subreddits?.map((subreddit, i) => (
              <SubredditRows key={i} index={i} topic={subreddit.topic} />
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
